# Generated by Django 4.2.4 on 2023-09-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='profile',
        ),
    ]
